services:
  base:
    build: ../base/
    container_name: benchmark_runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  python:
    build: ../
    container_name: python_benchmark
    volumes:
      - ../solutions/Python/output.txt:/output.txt

  node:
    build: ../
    container_name: node_benchmark
    volumes:
      - ../solutions/node/output.txt:/output.txt

  java:
    build: ../
    container_name: java_benchmark
    volumes:
      - ../solutions/java/output.txt:/output.txt

  cpp:
    build: ../
    container_name: cpp_benchmark
    volumes:
      - ../solutions/Cpp/output.txt:/output.txt

  rust:
    build: ../
    container_name: rust_benchmark
    volumes:
      - ../solutions/rust/output.txt:/output.txt

