services:
  base:
    build: .
    container_name: benchmark_runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  python:
    build: ../act2/Python
    container_name: python_benchmark
    volumes:
      - ../act2/Python/output.txt:/output.txt

  node:
    build: ../act2/node
    container_name: node_benchmark
    volumes:
      - ../act2/node/output.txt:/output.txt

  java:
    build: ../act2/java
    container_name: java_benchmark
    volumes:
      - ../act2/java/output.txt:/output.txt

  cpp:
    build: ../act2/Cpp
    container_name: cpp_benchmark
    volumes:
      - ../act2/Cpp/output.txt:/output.txt

  rust:
    build: ../act2/rust
    container_name: rust_benchmark
    volumes:
      - ../act2/rust/output.txt:/output.txt

