version: "3.8"

services:
  base:
    build: ./  # Construye desde la carpeta actual
    container_name: benchmark_runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  python:
    build: ./solutions/Python  # Ruta correcta al Dockerfile de Python
    container_name: python_benchmark
    volumes:
      - ./solutions/Python/output.txt:/output.txt

  node:
    build: ./solutions/Node  # Asegúrate de que "Node" es el nombre correcto de la carpeta
    container_name: node_benchmark
    volumes:
      - ./solutions/Node/output.txt:/output.txt

  java:
    build: ./solutions/Java
    container_name: java_benchmark
    volumes:
      - ./solutions/Java/output.txt:/output.txt

  cpp:
    build: ./solutions/Cpp  # Asegurar que "Cpp" es el nombre correcto
    container_name: cpp_benchmark
    volumes:
      - ./solutions/Cpp/output.txt:/output.txt

  rust:
    build: ./solutions/Rust  # Asegurar que "Rust" es el nombre correcto
    container_name: rust_benchmark
    volumes:
      - ./solutions/Rust/output.txt:/output.txt


