version: '3.8'

services:
  base:
    build: .
    container_name: benchmark_runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  python:
    build: ../act2/Python
    container_name: python_benchmark
    volumes:
      - ../act2/Python/output.txt:/output.txt

  node:
    build: ../act2/Node
    container_name: node_benchmark
    volumes:
      - ../act2/Node/output.txt:/output.txt

  java:
    build: ../act2/Java
    container_name: java_benchmark
    volumes:
      - ../act2/Java/output.txt:/output.txt

  cpp:
    build: ../act2/C++
    container_name: cpp_benchmark
    volumes:
      - ../act2/C++/output.txt:/output.txt

  rust:
    build: ../act2/Rust
    container_name: rust_benchmark
    volumes:
      - ../act2/Rust/output.txt:/output.txt



