version: "3.7"

services:
  python:
    build:
      context: ./  # Aquí va el contexto de construcción, puede estar vacío si ya has clonado el repositorio
    command: /bin/sh -c "cd /app/act2/Python && time python3 solution.py"
    container_name: solucion_python
    volumes:
      - ./act2:/app/act2  # Montamos el repositorio act2 dentro del contenedor en /app/act2
    networks:
      - benchmark_net

  cpp:
    build:
      context: ./  # Igualmente, aquí el contexto puede estar vacío
    command: /bin/sh -c "cd /app/act2/C++ && time ./solution"
    container_name: solucion_cpp
    volumes:
      - ./act2:/app/act2
    networks:
      - benchmark_net

  node:
    build:
      context: ./
    command: /bin/sh -c "cd /app/act2/Node && time node solution.js"
    container_name: solucion_node
    volumes:
      - ./act2:/app/act2
    networks:
      - benchmark_net

  java:
    build:
      context: ./ 
    command: /bin/sh -c "cd /app/act2/Java && time java Solution"
    container_name: solucion_java
    volumes:
      - ./act2:/app/act2
    networks:
      - benchmark_net

  rust:
    build:
      context: ./ 
    command: /bin/sh -c "cd /app/act2/Rust && time ./solution"
    container_name: solucion_rust
    volumes:
      - ./act2:/app/act2
    networks:
      - benchmark_net

networks:
  benchmark_net:
    driver: bridge

